### ISSUE TITLE
Missed parameters and context validation in external service

### ISSUE THREAD

**Issue by volodymyrdovhan** [cbluesprl/moodle-local_copygroups#6]
Hello,

In external service _get_courses.php_ missed security validations: 

1. Required parameters validations: https://moodledev.io/docs/4.5/apis/subsystems/external/writing-a-service#parameter-validation
2. Required context and capabilities validation: https://moodledev.io/docs/4.5/apis/subsystems/external/writing-a-service#context-and-capability-checks
3. In the parameters description should be set VALUE_REQUIRED, VALUE_OPTIONAL, or VALUE_DEFAULT: https://moodledev.io/docs/4.5/apis/subsystems/external/writing-a-service#required-optional-or-default-value

https://github.com/cbluesprl/moodle-local_copygroups/blob/main/classes/external/get_courses.php

**Comment by volodymyrdovhan** [comment]
Please leave a comment once the issue is fixed, and I will proceed with a quick review.

Thank you!

**Comment by Fleoxi** [comment]
Hello,

The issue you raised has been corrected.
The fix has been deployed in both branches (main & MOODLE_400_STABLE).
