### ISSUE TITLE
classes "copygroups_form" and "copydistinctgroups_form" are not namespaced and do not follow frankenstyle guidelines

### ISSUE THREAD

**Issue by danmarsden** [cbluesprl/moodle-local_copygroups#7]
It would be good to namespace these classes correctly so that class-autoloading works and you don't have to include them using require_once() calls:
for more information see:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle

and the older moodledocs page here which is still partly relevant:
https://docs.moodle.org/dev/Automatic_class_loading

**Comment by Fleoxi** [comment]
Hello @danmarsden

Namespace and class names have been adapted to be autoloaded by Moodle.

Kind regards,
